name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image 
      uses: actions/checkout@v3
    - run: docker build . --file Dockerfile --tag jusefn/weather-app:$(date +%s)
    - run: docker tag jusefn/weather-backend jusefn/weather-backend:latest
    - run: docker push jusefn/weather-backend:latest
